### ISSUE TITLE
Reference Section Issue (Report)

### ISSUE THREAD

**Issue by atugman555** [cybertraining-dsc/fa20-523-323#1]
In my report.md I currently have 2 comments, not following template and a comment to the reference section.  I have compared my reference section to other students and can not see any difference.  Can you please point out in detail where the error appears.  Additionally, each reference appears to render on its own line through the report website.

**Comment by laszewsk** [comment]
template: add the tags compare template carefully
refs: i think i fixed refs a while back

**Comment by atugman555** [comment]
ERROR: Please indicate final submission with `Status: final` after the Check Report Icon. Please see https://raw.githubusercontent.com/cybertraining-dsc/fa20-523-312/main/project/project.md for an example where to place the Status: flag

Is this what you are referencing by tag?

**Comment by laszewsk** [comment]
Please take a look at the template

**Comment by laszewsk** [comment]
we have posted a video if you do not know where to find it.

**Comment by atugman555** [comment]
Resolved, thank you for your help!
