### ISSUE TITLE
StopWatch

### ISSUE THREAD

**Issue by laszewsk** [cybertraining-dsc/fa20-523-323#4]
See video and ipynb sample on how to use the cloudmesh timer. STart stop needs to be from StopWatch as you do not use functions. This was clearly explained

**Comment by laszewsk** [comment]
Add a sentance and refernce to the Repo:

The cloudmesh benchmark [^cloudmesh-benchmark] framework was used to create the benchmarks.

## ??. Refernces

[^cloudmesh-benchmark]: Gregor von Laszewski, Cloudmesh StopWatch and Benchmark from the Cloudmesh Common Library, <https://github.com/cloudmesh/cloudmesh-common>

**Comment by laszewsk** [comment]
I added the ref for you

**Comment by atugman555** [comment]
Thank you, I have made the required changes and resubmitted.
